controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

get_department:
  path: "/getDepartment/{id}"
  controller: App\Controller\AdsController::getDepartment

get_cities:
  path: "/get-cities/{departmentNumber}"
  controller: App\Controller\AdsController::getCities
app_ad_delete:
  path: /my-ads/delete/{adId}
  controller: App\Controller\AdsController::deleteAd
  methods: [DELETE]
